name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install vnu-jar
        run: npm install --save-dev vnu-jar

      - name: Run HTML Validator
        run: |
          java -jar node_modules/vnu-jar/build/dist/vnu.jar \
            --errors-only \
            --skip-non-html \
            --no-stream \
            --Werror \
            .

      - name: Print validation finished
        run: echo "HTML validation complete."
